# Generated by Django 4.1.3 on 2022-12-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Movie Title')),
                ('release_date', models.DateField()),
                ('description', models.CharField(max_length=100, verbose_name='Synopsis')),
            ],
        ),
    ]
